---
- name: upgrade all packages
  become: centos
  yum: name=* state=latest

- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
      - tmux
      - zsh
      - vim 
      - htop

- name: Add authorized keys for deploy user
  authorized_key: user={{ ansible_user }} key="{{ lookup('file', item) }}"
  with_items: public_keys


