---

- name: Create user
  become: yes
  become_user: root
  user:
    name: "{{ user }}"
    groups: wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: /bin/zsh

- name: Upload auth keys
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '~/.ssh/one_pl.pub') }}"

- name: Zsh configuration
  get_url: url={{ item.url }} dest={{ item.dst }} force=yes
  with_items:
      - {url: "http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc", dst: ~/.zshrc}
      - {url: "http://git.grml.org/f/grml-etc-core/etc/skel/.zshrc", dst: ~/.zshrc.local}

- name: Get tmux conf
  get_url: url="{{ tmux_url }}" dest=~/.tmux.conf force=yes

- name: Get git conf
  get_url: url="{{ git_conf_url }}" dest=~/.gitconfig force=yes

- name: Get vimrc
  get_url: url="{{ vimrc_url}}" dest=~/.vimrc force=yes

- name: Get vundle
  git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim

- name: Install vim plugins
  command: vim +PluginInstall +qall chdir=/tmp 700fcc04-759d-4573-9c74-52d0464f4df7
  register: result
  no_log: True
